name: cr37

dependencies:
  - python=3.7
  - tensorflow=1.15.0
  - scipy
  - numpy
  - pip=20.2.4
  - pip:
      # environment dependencies
      - aenum
      - networkx
      - triangle
      - Polygon3
      - pybind11
      - setuptools==50.3.2
      # learning dependencies
      - gym
      - stable_baselines
      # CommonRoad packages
      - commonroad-io==2021.4
      - commonroad-vehicle-models
      - commonroad-route-planner==2022.1
      # Evaluation dependencies
      - SALib==1.3.13
      # parser for setup.py
      - pyparsing==2.4.7
      # for inverse constraint RL
      - wandb==0.10.12
      - torch==1.5.0
      - matplotlib==3.3.2
      - cloudpickle==1.2.2
      - tqdm
      - pandas
      - pillow
      - psutil
      - mpl-scatter-density
      - imageio
